export const translations = {
  vi: {
    welcome: 'Chào mừng bạn đến với Quảng Ninh! Bạn muốn đi đâu hôm nay?',
    inputPlaceholder: 'Nhập yêu cầu của bạn...',
    error: 'Lỗi',
    connectionError: 'Không thể gửi yêu cầu.',
    languageSwitch: 'English',
    subtitle: 'Trợ lý du lịch thông minh',
    status: 'Trực tuyến',
    location: 'Quảng Ninh, Việt Nam',
    welcomeTitle: 'Chào mừng đến với QBot AI!',
    welcomeSubtitle: 'Trợ lý du lịch thông minh của bạn tại Quảng Ninh',
    welcomeDescription: 'Tôi sẽ giúp bạn khám phá những điểm đến tuyệt vời, tìm kiếm nhà hàng ngon và lên kế hoạch cho chuyến du lịch hoàn hảo.',
    tryButton: 'Dùng thử',
    loginPrompt: 'Đăng nhập để lưu lịch sử chat',
    loginNow: 'Đăng nhập ngay',
    registerNow: 'Đăng ký ngay',
    login: 'Đăng nhập',
    register: 'Đăng ký',
    email: 'Email',
    password: 'Mật khẩu',
    noAccount: 'Chưa có tài khoản',
    hasAccount: 'Đã có tài khoản',
    enterEmail: 'Nhập email',
    enterPassword: 'Nhập mật khẩu',
    loginWithGoogle: 'Đăng nhập với Google',
    loginWithFacebook: 'Đăng nhập với Facebook',
    name: 'Họ tên',
    enterName: 'Nhập họ tên',
    confirmpPassword: 'Xác nhận mật khẩu',
    enterConfirmPassword: 'Nhập lại mật khẩu',
    welcomeGreeting: 'Xin chào! Tôi là QBot AI, trợ lý du lịch của bạn!'
  },
  en: {
    welcome: 'Welcome to Quang Ninh! Where would you like to go today?',
    inputPlaceholder: 'Enter your request...',
    error: 'Error',
    connectionError: 'Could not send request.',
    languageSwitch: 'Tiếng Việt',
    subtitle: 'Smart Travel Assistant',
    status: 'Online',
    location: 'Quang Ninh, Vietnam',
    welcomeTitle: 'Welcome to QBot AI!',
    welcomeSubtitle: 'Your Smart Travel Assistant in Quang Ninh',
    welcomeDescription: 'I will help you discover amazing destinations, find great restaurants, and plan your perfect trip.',
    tryButton: 'Triel Use',
    loginPrompt: 'Log in to save chat history',
    loginNow: 'Login now',
    registerNow: 'Register now',
    login: 'Login',
    register: 'Register',
    email: 'Email',
    password: 'Password',
    noAccount: 'No account yet',
    hasAccount: 'Already have an account',
    enterEmail: 'Enter email',
    enterPassword: 'Enter password',
    loginWithGoogle: 'Login with Google',
    loginWithFacebook: 'Login with Facebook',
    name: 'Name',
    enterName: 'Enter name',
    confirmPassword: 'Confirm password',
    enterConfirmPassword: 'Re-enter password',
    welcomeGreeting: 'Hello! I am QBot AI, your travel assistant!'
  },
};

export const chatbotConfig = {
  name: 'QBot AI',
  logo: "🤖",
  theme: {
    primary: 'blue',
    secondary: 'teal',
    accent: 'purple',
  },
  features: {
    showStatus: true,
    showLocation: true,
    showSubtitle: true,
    showLogo: true,
    animated: true,
    voiceEnabled: true,
  },
  customStyles: {
    headerBg: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    headerHeight: { base: '100px', md: '120px' },
    logoSize: { base: '40px', md: '50px' },
  },
};